SEND("GET TX PREDEFINE-EDID\r")
send("SET TX PREDEFINE-EDID 1080P60-2.0\r")
send("GET TX PREDEFINE-EDID\r")

send("GET TX 4K-HANDLE\r")
send("SET TX 4K-HANDLE 1080P\r")
send("GET TX 4K-HANDLE\r")

send("GET TX HDCP-OPTION\r")
send("SET TX HDCP-OPTION FORCE-OFF\r")
send("GET TX HDCP-OPTION\r")

send("GET TX NO-SIGNAL-HANDLE\r")
send("SET TX NO-SIGNAL-HANDLE NO-TIMING\r")
send("GET TX NO-SIGNAL-HANDLE\r")